name: lupine
description: "A drive app to store your files in a decentralized way."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  crypto: ^3.0.6
  desktop_drop: ^0.6.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_dropzone_platform_interface: ^2.2.0
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  hex: ^0.2.0
  intl: any
  mime: ^2.0.0
  path: ^1.9.1
  lupine_sdk: ^2.0.1
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  pointycastle: ^4.0.0
  bech32: ^0.2.2
  system_theme: ^3.1.2
  window_manager: ^0.5.0
  toastification: ^3.0.2
  ndk: ^0.5.1
  url_strategy: ^0.3.0
  flutter_svg: ^2.2.1
  nostr_widgets: ^1.1.0
  sembast_cache_manager: ^1.0.3
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  get_storage: ^2.1.1
  file_saver: ^0.3.1
  share_plus: ^12.0.0
  nip19: ^0.2.0
  nip49: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/lupinepath.svg 
