name: lupine
description: "A drive app to store your files in a decentralized way."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  crypto: ^3.0.7
  desktop_drop: ^0.7.0
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  flutter_dropzone_platform_interface: ^2.2.0
  flutter_localizations:
    sdk: flutter
  get: ^4.7.3
  hex: ^0.2.0
  intl: any
  mime: ^2.0.0
  path: ^1.9.1
  lupine_sdk: ^2.0.2
  path_provider: ^2.1.5
  flutter_secure_storage: ^10.0.0
  pointycastle: ^4.0.0
  bech32: ^0.2.2
  system_theme: ^3.2.0
  window_manager: ^0.5.1
  toastification: ^3.0.3
  ndk: 0.6.1-dev.6
  url_strategy: ^0.3.0
  flutter_svg: ^2.2.3
  nostr_widgets: ^1.1.6
  sembast_cache_manager: ^1.0.5
  sembast: ^3.8.6
  sembast_web: ^2.4.3
  get_storage: ^2.1.1
  file_saver: ^0.3.1
  share_plus: ^12.0.1
  nip49: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - images/lupinepath.svg 
