name: lupine
description: "A drive app to store your files in a decentralized way."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.7.2

dependencies:
  crypto: ^3.0.6
  desktop_drop: ^0.6.0
  encrypt: ^5.0.3
  file_picker: ^10.1.9
  flutter:
    sdk: flutter
  flutter_dropzone_platform_interface: ^2.2.0
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  hex: ^0.2.0
  intl: any
  mime: ^2.0.0
  path: ^1.9.1
  lupine_sdk: ^1.0.2
  # lupine_sdk:
  #   path:
  #     ../lupine_sdk
  path_provider: ^2.1.5
  flutter_secure_storage: ^9.2.4
  pointycastle: ^3.9.1
  bech32: ^0.2.2
  system_theme: ^3.1.2
  window_manager: ^0.5.0
  toastification: ^3.0.2
  ndk: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
